# Generated by Django 4.1.6 on 2023-02-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_scope_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='topic',
        ),
    ]
